services:
  postgres:
    container_name: postgres
    image: postgres:16
    restart: always
    ports:
      - 5432:5432
    volumes:
      - ./data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=00000000
      - POSTGRES_DB=postgres
