version: "3"

services:
  ubuntu:
    image: ubuntu:18.04
    container_name: ubuntu_nginx
    tty: true

    ports:
     - "2200:22"
     - "9000:9000"
    volumes:
     - ./conf.d:/etc/nginx/conf.d
     - /Users/cate/workspace/project_pacs:/project_pacs
