version: '3.1'

services:
  mongo:
    container_name: 'mongo-pacs'
    image: mongo
    restart: always
    ports:
      - 27018:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_ROOT_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_ROOT_PASSWORD}
      - MONGO_INITDB_DATABASE=cloudpacs
    volumes:
      - ./data:/data/db

